# Generated by Django 4.2.3 on 2023-07-20 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PerspectiveCub', '0004_remove_favorites_user_favorites_saver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='saver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='saver', to=settings.AUTH_USER_MODEL),
        ),
    ]
